<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>HostProbe.WpfHwnd</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HostProbe.Core\HostProbe.Core.csproj" />
  </ItemGroup>

</Project>
