#!/usr/bin/env python3
"""Generate CharacterWidth's tables from the Unicode Character Database.

A width table decides which column the cursor is in. Hand-written, it is a list of ranges
somebody transcribed once and nobody will ever diff against a new Unicode release; generated,
it is a file anybody can rebuild and compare. So this exists, it is committed beside what it
produces, and the version it read is written into the output.

Usage:
    python tools/generate-width-table.py [--ucd <dir>] [--out <file>]

With no --ucd it downloads the three files it needs from unicode.org. With one it reads them
from disk, which is how this runs on a machine with no network and how a release is pinned to
files somebody kept.

The three inputs and what each decides:
  EastAsianWidth.txt          W and F are two columns wide.
  emoji-data.txt              Emoji_Presentation is two columns wide, whatever its East Asian
                              width says - which for most emoji is Neutral.
  DerivedGeneralCategory.txt  Mn and Me take no column of their own: they attach to the cell
                              before them, and a host advancing its cursor for one would be
                              disagreeing with every terminal there is.
"""

import argparse
import os
import re
import sys
import urllib.request

BASE = "https://www.unicode.org/Public/UCD/latest/ucd/"
FILES = {
    "EastAsianWidth.txt": BASE + "EastAsianWidth.txt",
    "emoji-data.txt": BASE + "emoji/emoji-data.txt",
    "DerivedGeneralCategory.txt": BASE + "extracted/DerivedGeneralCategory.txt",
}

RANGE = re.compile(r"^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([^#\s]+)")
VERSION = re.compile(r"^#\s*\w+-([0-9]+\.[0-9]+\.[0-9]+)\.txt")


def load(name, ucd):
    if ucd:
        with open(os.path.join(ucd, name), encoding="utf-8") as handle:
            return handle.read()

    with urllib.request.urlopen(FILES[name], timeout=60) as response:
        return response.read().decode("utf-8")


def version_of(text, fallback):
    for line in text.splitlines()[:8]:
        found = VERSION.match(line)
        if found:
            return found.group(1)
    return fallback


def select(text, wanted):
    """Every codepoint whose property is in `wanted`, as a set of (first, last) pairs."""
    found = set()

    for line in text.splitlines():
        line = line.split("#")[0]
        match = RANGE.match(line)

        if not match:
            continue

        if match.group(3) not in wanted:
            continue

        first = int(match.group(1), 16)
        last = int(match.group(2), 16) if match.group(2) else first
        found.add((first, last))

    return found


def merge(pairs):
    """Sort and coalesce, so neighbours become one range and the table stays a binary search."""
    ordered = sorted(pairs)
    merged = []

    for first, last in ordered:
        if merged and first <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], last)
        else:
            merged.append([first, last])

    return merged


def emit(name, ranges, out):
    out.append(f"    private static readonly int[] {name} =")
    out.append("    [")

    for first, last in ranges:
        out.append(f"        0x{first:04X}, 0x{last:04X},")

    out.append("    ];")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ucd", help="read the UCD files from this directory instead of the network")
    parser.add_argument("--out", default="src/Quickshell.Terminal/CharacterWidth.Generated.cs")
    arguments = parser.parse_args()

    eaw = load("EastAsianWidth.txt", arguments.ucd)
    emoji = load("emoji-data.txt", arguments.ucd)
    categories = load("DerivedGeneralCategory.txt", arguments.ucd)

    unicode_version = version_of(eaw, version_of(categories, "unknown"))

    wide = select(eaw, {"W", "F"}) | select(emoji, {"Emoji_Presentation"})
    zero = select(categories, {"Mn", "Me"})

    wide = merge(wide)
    zero = merge(zero)

    out = [
        "// <auto-generated>",
        "//     Written by tools/generate-width-table.py from the Unicode Character Database.",
        f"//     Unicode {unicode_version}. Rebuild rather than edit: a hand-corrected range is a",
        "//     correction the next release silently discards.",
        "// </auto-generated>",
        "",
        "namespace Quickshell.Terminal;",
        "",
        "public static partial class CharacterWidth",
        "{",
        "    /// <summary>The Unicode release these tables were generated from.</summary>",
        f'    public const string UnicodeVersion = "{unicode_version}";',
        "",
        "    /// <summary>",
        "    /// Codepoints that take two columns: East Asian Wide and Fullwidth, plus everything",
        "    /// Unicode gives emoji presentation by default. Sorted pairs, so the lookup is a binary",
        "    /// search over a flat array rather than a walk over objects.",
        "    /// </summary>",
    ]

    emit("WideRanges", wide, out)
    out += [
        "",
        "    /// <summary>",
        "    /// Codepoints that take no column: non-spacing and enclosing marks, which attach to the",
        "    /// cell before them rather than taking one of their own.",
        "    /// </summary>",
    ]
    emit("ZeroRanges", zero, out)
    out += ["}", ""]

    with open(arguments.out, "w", encoding="utf-8", newline="\r\n") as handle:
        handle.write("\n".join(out))

    print(f"Unicode {unicode_version}: {len(wide)} wide ranges, {len(zero)} zero-width ranges "
          f"-> {arguments.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
